import {Card, DebtPlan, FinancialAccount, FinancialPreferences, GoalContribution, IncomeRule, InstallmentCommitment, RecurringExpense,RecurringOverride, SavingsGoal, UiPreferences} from '../../core/src/types';
import {StatementImport,TransactionRecord} from './contracts';
import {CardSnapshot} from './financial-snapshots';

export interface FinanceRepository {
  commitStatementImport(statement:StatementImport,transactions:TransactionRecord[],snapshot?:CardSnapshot):Promise<void>;
  contributeToGoal(contribution:GoalContribution):Promise<void>;
  listCards(includeArchived?:boolean): Promise<Card[]>;
  getCard(id:string): Promise<Card|undefined>;
  saveCard(card:Card):Promise<void>;
  updateCard(card:Card):Promise<void>;
  listCardSnapshots():Promise<CardSnapshot[]>;
  getCardSnapshot(cardId:string):Promise<CardSnapshot|undefined>;
  upsertCardSnapshot(snapshot:CardSnapshot):Promise<void>;
  listDebtPlans(): Promise<DebtPlan[]>;
  listIncomeRules():Promise<IncomeRule[]>;
  listInstallmentCommitments():Promise<InstallmentCommitment[]>;
  getPreferences():Promise<FinancialPreferences>;
  savePreferences(preferences:FinancialPreferences):Promise<void>;
  getDebtPlan(id:string): Promise<DebtPlan|undefined>;
  listRecurring(includeArchived?:boolean): Promise<RecurringExpense[]>;
  listRecurringOverrides():Promise<RecurringOverride[]>;
  saveRecurringOverride(override:RecurringOverride):Promise<void>;
  listTransactions(): Promise<TransactionRecord[]>;
  saveTransaction(tx:TransactionRecord): Promise<void>;
  listImports():Promise<StatementImport[]>;
  getImport(id:string):Promise<StatementImport|undefined>;
  saveImport(statementImport:StatementImport):Promise<void>;
  updateImport(statementImport:StatementImport):Promise<void>;
  listAccounts(includeArchived?:boolean):Promise<FinancialAccount[]>;
  getAccount(id:string):Promise<FinancialAccount|undefined>;
  saveAccount(account:FinancialAccount):Promise<void>;
  updateAccount(account:FinancialAccount):Promise<void>;
  listGoals(includeArchived?:boolean):Promise<SavingsGoal[]>;
  getGoal(id:string):Promise<SavingsGoal|undefined>;
  saveGoal(goal:SavingsGoal):Promise<void>;
  updateGoal(goal:SavingsGoal):Promise<void>;
  listGoalContributions(goalId?:string):Promise<GoalContribution[]>;
  saveGoalContribution(contribution:GoalContribution):Promise<void>;
  getUiPreferences():Promise<UiPreferences>;
  saveUiPreferences(preferences:UiPreferences):Promise<void>;
}
